### PR TITLE
added a working html CSS and JavaScript site

### PR DESCRIPTION
**Pull request by prashant67690**
added the fully working site with the required files in the folder , the site contains the listed features 
1. site contains beautiful and efficient CSS implementation
2. used JavaScript for the smooth scrolling feature  
3. used the google map api for the map at the footer for locating the office.

### CODE REVIEW

**Comment by invad3r07** [comment]
Kindly give deployed link
https://github.com/shubham7668/WebDev#rules
& make sure to follow rules

**Comment by prashant67690** [comment]
ok will do it

**Comment by prashant67690** [comment]
hello there i have uploaded the working link and have followed all the rules for contribution thank you for your help

**Comment by invad3r07** [comment]
is it yours?
image

I am marking this pr as invalid as i am unable to find your proof of work.

**Comment by invad3r07** [comment]
If I am mistaken then feel free to comment

**Pull request closed without merging**
