### PR TITLE
project-added 

### PR DESCRIPTION
**Pull request by mayank-del**
@shubham7668  please check my html canvas project and merge

### CODE REVIEW

**Comment by mayank-del** [comment]
resolves #15

**Comment by shubham7668** [comment]
Drop deployed link @mayank-del

**Review by shubham7668 — APPROVED** [review]

**Comment by mayank-del** [comment]
I have to deploy it?
and where?

**Comment by shubham7668** [comment]
Yes
You can deploy it wherever you want Netlify,Heroku,Github

Just give us deployed link for proof of work

**Comment by mayank-del** [comment]
https://mayank-del.github.io/rectangle-generator/

Github Deploy Link
Now, You can See it @shubham7668

**Review by shubham7668 — APPROVED** [review]
Looks good to me

**Pull request merged**
